# Configuración básica del servidor
server.port=8080

# Configuración básica de la base de datos (por ejemplo, H2)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuración básica de logging
logging.level.org.springframework=INFO
logging.level.com.pda=DEBUG

