# Configuraci�n b�sica del servidor
server.port=25565

# Configuraci�n b�sica de la base de datos (por ejemplo, H2)
spring.datasource.url=jdbc:postgresql://localhost:5432/pdadb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=pdadbpsql
spring.datasource.password=8?Asdu.92xfg
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuraci�n b�sica de logging
logging.level.org.springframework=INFO
logging.level.com.pda=DEBUG

